DROP TABLE IF EXISTS workouts CASCADE;

CREATE TABLE workouts (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  day_id INTEGER UNIQUE REFERENCES days(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description text,
  picture_url VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);
