INSERT INTO workouts (workout_date, picture_url, description, title, user_id)
VALUES ('2023-04-01', 'localhost:3000/Img/1%20First%20Day.jpg', 'Today is the first day I embark on my gym journey to try to improve my mental, physical, and nutritional health!', 'Day 1', 1),
       ('2023-04-07', 'https://randomuser.me/api/portraits/men/2.jpg',  'Tried one of the most popular exercises today. Time to make Arnold Proud!', 'Exciting prospects', 1),
       ('2023-04-12', 'https://randomuser.me/api/portraits/women/3.jpg',  'I do not understand why some people enjoy the cardio business....', 'Cardi No', 1),
       ('2023-04-15', 'https://randomuser.me/api/portraits/men/4.jpg',  'I watched a video someone lifting 500kg and wanted to see how hard it is myself. Needless to say, I cannot lift 500kg.', 'Lifting Deads', 1),
       ('2023-04-20', 'https://randomuser.me/api/portraits/men/4.jpg', 'Spreading my wings so one day I can fly to the heavens', 'I believe I can fly', 1),
       ('2023-04-25', 'https://randomuser.me/api/portraits/men/4.jpg', 'Learned more about how to target the different fibers in my muscles. Slow and easy wins the race', 'Chest Day Best Day', 1),
       ('2023-04-28', 'https://randomuser.me/api/portraits/men/4.jpg', 'Have to make sure I train my legs so my friends won''t make fun of me', 'First Leg Day', 1),
       ('2023-04-29', 'https://randomuser.me/api/portraits/men/4.jpg', 'Leg Day was no joke, I made sure to roll out my knots today.', '#SORE', 1),
       ('2023-05-01', 'https://randomuser.me/api/portraits/men/4.jpg', 'Getting over my fear of touching Dumbbells today. Balancing the weight is much harder than I thought!', 'Graduated to Free Weights', 1),
       ('2023-05-02', 'https://randomuser.me/api/portraits/men/4.jpg', 'I found that working with Dumbbells is easier on my joints than a barbell!', 'Mobility', 1),
       ('2023-05-03', 'https://randomuser.me/api/portraits/men/4.jpg', 'One Day I''ll be able to do a pull up!', 'Soaring', 1),
       ('2023-05-07', 'https://randomuser.me/api/portraits/men/4.jpg', 'Starting to get addicted to leg day. The noobie gains are real!', 'Addiction', 1),
       ('2023-05-08', 'https://randomuser.me/api/portraits/men/4.jpg', 'Can''t forget to stretch after such intense workouts!', 'Intense Workouts, Intense Stretching', 1),
       ('2023-05-10', 'https://randomuser.me/api/portraits/men/4.jpg', 'Machines are kind of fun', 'Always learning', 1),
       ('2023-05-12', 'https://randomuser.me/api/portraits/men/4.jpg', 'There''s so many different accessories that I didn''t know existed!', 'What''s a Landmine?!', 1),
       ('2023-05-13', 'https://randomuser.me/api/portraits/men/4.jpg', 'My quads are strong but I need to train my hammies too!', 'Balancing my legs out', 1),
       ('2023-05-15', 'https://randomuser.me/api/portraits/men/4.jpg', 'I watched a youngling touch a very heavy weight today, I hope I can get as strong as them one day.', 'Big Boi weights', 1),
       ('2023-05-17', 'https://randomuser.me/api/portraits/men/4.jpg', 'My legs are getting stronger! Graduated from a yellow plate to a red plate!', 'Upgrading!', 1),
       ('2023-05-18', 'https://randomuser.me/api/portraits/men/4.jpg', 'I noticed there''s so much respect and etiquette in the gym community. I really feel at home', 'Respect', 1),
       ('2023-05-19', 'https://randomuser.me/api/portraits/men/4.jpg', 'I''m addicted to training legs', 'The addiction is real', 1),
       ('2023-05-20', 'https://randomuser.me/api/portraits/men/4.jpg', 'I have a problem, I keep training my legs.', 'My pants don''t fit anymore', 1),
       ('2023-05-23', 'https://randomuser.me/api/portraits/men/4.jpg', 'Wanted to try a max lift today. I was much stronger than I thought! #POWERRR', 'PR', 1);